// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KafkaAvroProducer.Abstractions.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class PokeAvroModel : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PokeAvroModel"",""namespace"":""KafkaAvroProducer.Abstractions.Models"",""fields"":[{""name"":""Id"",""type"":""int""},{""name"":""Name"",""type"":""string""},{""name"":""Height"",""type"":""int""},{""name"":""Weight"",""type"":""int""},{""name"":""BaseExperience"",""type"":""int""},{""name"":""Sprite"",""type"":""string""},{""name"":""Abilities"",""type"":""string""},{""name"":""Species"",""type"":""string""},{""name"":""Types"",""type"":""string""},{""name"":""Stats"",""type"":{""type"":""array"",""items"":""string""}}]}");
		private int _Id;
		private string _Name;
		private int _Height;
		private int _Weight;
		private int _BaseExperience;
		private string _Sprite;
		private string _Abilities;
		private string _Species;
		private string _Types;
		private IList<System.String> _Stats;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PokeAvroModel._SCHEMA;
			}
		}
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public int Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				this._Height = value;
			}
		}
		public int Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				this._Weight = value;
			}
		}
		public int BaseExperience
		{
			get
			{
				return this._BaseExperience;
			}
			set
			{
				this._BaseExperience = value;
			}
		}
		public string Sprite
		{
			get
			{
				return this._Sprite;
			}
			set
			{
				this._Sprite = value;
			}
		}
		public string Abilities
		{
			get
			{
				return this._Abilities;
			}
			set
			{
				this._Abilities = value;
			}
		}
		public string Species
		{
			get
			{
				return this._Species;
			}
			set
			{
				this._Species = value;
			}
		}
		public string Types
		{
			get
			{
				return this._Types;
			}
			set
			{
				this._Types = value;
			}
		}
		public IList<System.String> Stats
		{
			get
			{
				return this._Stats;
			}
			set
			{
				this._Stats = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Name;
			case 2: return this.Height;
			case 3: return this.Weight;
			case 4: return this.BaseExperience;
			case 5: return this.Sprite;
			case 6: return this.Abilities;
			case 7: return this.Species;
			case 8: return this.Types;
			case 9: return this.Stats;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int32)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.Height = (System.Int32)fieldValue; break;
			case 3: this.Weight = (System.Int32)fieldValue; break;
			case 4: this.BaseExperience = (System.Int32)fieldValue; break;
			case 5: this.Sprite = (System.String)fieldValue; break;
			case 6: this.Abilities = (System.String)fieldValue; break;
			case 7: this.Species = (System.String)fieldValue; break;
			case 8: this.Types = (System.String)fieldValue; break;
			case 9: this.Stats = (IList<System.String>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
